### ISSUE TITLE
Organize Jewels Image into cells of equal width and height

### ISSUE THREAD

**Issue by ironsigma** [ironsigma/three-jewels#1]
### Description

The current `gems.png` has the images of the jewels in roughly a grid. But due to the variable size of each jewel they are not in an exact grid. We'll need this to make it easier to "cut" them up once we load up the entire image. 

### Acceptance Criteria 

- Create a transparent PNG image of 720x480
- Copy each jewel from the existing `gems.png` to the new transparent image.
- Each jewel should take up no more than 120x120 pixels in the new image.
- Each jewel should be centered in the 120x120 cell
- No lines, borders, or any other dividers should be present in the final image.

**Comment by enzomzaocv** [comment]
Hello, I'll be glad to help, please assign me this issue.

**Comment by ironsigma** [comment]
Sure you got it
