### ISSUE TITLE
Exception thrown when loading/saving high-score file when running from JAR

### ISSUE THREAD

**Issue by ironsigma** [ironsigma/three-jewels#12]
If we run the game from the jar: `java -jar jewels-0.1.0-SNAPSHOT-jar-with-dependencies.jar` the game throws a `java.io.FileNotFoundException` when trying to load or save a high-score file.

This is due to using `ScorePanel.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath()` as the path to the file. we should use [java.util.prefs](https://docs.oracle.com/javase/8/docs/api/java/util/prefs/package-summary.html) instead.

**Comment by rejwr** [comment]
Hi, I can try to fix this issue with using Java Preferences.

**Comment by ironsigma** [comment]
Fixed
