### ISSUE TITLE
Keep Track of Player Score

### ISSUE THREAD

**Issue by ironsigma** [ironsigma/three-jewels#7]
### Description
Right now when jewels are matched, they're only removed from the board. We need to keep track of a player score, and assign points for removing jewels off the board.

### Acceptance Criteria
- Shift the grid down to make space for the score.
- Draw the score in the top right corner of the new space.
- All mouse clicks to grid cell calculations must account for the grid shift.
- Every time a player matches three jewels, they will be awarded 100 points and 50 points for each additional jewel over three.

**Comment by rejwr** [comment]
Hi i would like to work on this issue. Please assign it to me. Thank you.

**Comment by ironsigma** [comment]
@rejwr It's yours!
